mulesoft/mule-extensions-api

pom.xml
Added URL, license, developer information and scm Maven tags
Add GPG signature plugin
Add Maven javadoc and sources plugin
Change groupId to org.mule.extensions
=> MULE-8435   Check if Ext-api jars are Maven Central compliant

mule-extensions-api/src/main/java/org/mule/extension/api/introspection/declaration/type/ExtensionsFieldHandler.java
_ Fixing reference to core class
=> MULE-9585: Apply new package naming schema

mule-extensions-api-persistence/src/test/resources/metadata/failure-result.json, mule-extensions-api-persistence/src/test/resources/metadata/success-result-descriptor.json, mule-extensions-api-persistence/src/test/resources/metadata/success-result-keys.json
Requires https://github.com/mulesoft/mule-api/pull/20 to be merged
=> MULE-9406: Fix typo

mule-extensions-api-persistence/src/main/java/org/mule/runtime/extension/api/persistence/metadata/MetadataKeysResultJsonSerializer.java, mule-extensions-api-persistence/src/test/java/org/mule/runtime/extension/api/persistence/MetadataResultPersistenceTestCase.java, mule-extensions-api-persistence/src/test/resources/metadata/success-result-keys.json, mule-extensions-api-persistence/src/test/resources/metadata/success-result-multilevel-keys.json, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/introspection/metadata/NullMetadataKey.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/introspection/metadata/NullMetadataResolver.java
Requires https://github.com/mulesoft/mule-api/pull/28
=> MULE-9820: Add the concept of part name/level to MetadataKeys

mule-extensions-api/src/main/resources/META-INF/mule-module.properties
_ Exporting extra package needed on extensions support
=> MULE-9869: Ensure that modules are exporting the right packages

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/OperationContext.java
parameters and not passed parameters
=> MULE-10024: OperationContext should distinguish between null-value

mule-extensions-api-dsql/README.md, mule-extensions-api-dsql/pom.xml, pom.xml
Fixing formatter problems when generating ANTLR classes, removed from the DSQL module
=> MULE-10259: Add DSQL into the SDK

mule-extensions-api-persistence/src/main/java/org/mule/runtime/extension/internal/persistence/XmlDslModelTypeAdapter.java, mule-extensions-api-persistence/src/test/resources/extension/list-of-serialized-extension-model.json, mule-extensions-api-persistence/src/test/resources/extension/serialized-extension-model.json, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/annotation/dsl/xml/Xml.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/dsl/syntax/DslElementSyntax.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/util/XmlModelUtils.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/dsl/syntax/DslElementSyntaxBuilder.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/dsl/syntax/XmlDslSyntaxResolver.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/api/dsl/BaseXmlDeclarationTestCase.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/api/dsl/ComponentsXmlDeclarationTestCase.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/api/dsl/ParameterXmlDeclarationTestCase.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/api/dsl/TypeXmlDeclarationTestCase.java
depends on https://github.com/mulesoft/mule-api/pull/162
=> MULE-11856: @Xml annotation attributes renaming

mule-extensions-api-dsql/pom.xml, mule-extensions-api-persistence/pom.xml, mule-extensions-api/pom.xml, pom.xml
depends on https://github.com/mulesoft/metadata-model-api/pull/62 and https://github.com/mulesoft/mule-api/pull/169
=> MULE-11289: renaming groupsIds

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/client/ExtensionsClient.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/operation/Result.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/process/CompletionCallback.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/source/Source.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/source/SourceCallback.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/source/SourceCallbackContext.java
Requires merging at the same time in mule, mule-ee, mule-api, mule-compatibility-plugin and mule-extensions-api
=> MULE-10774: make attributes a TypedValue

mule-extensions-api-persistence/pom.xml, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/ExtensionConstants.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/annotation/param/display/Placement.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/SourceDeclarationEnricher.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/StreamingDeclarationEnricher.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/TransactionalDeclarationEnricher.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/internal/loader/TransactionalDeclarationEnricherTestCase.java
Cleanup placement/layout of enriched content.
=> Clean up layout

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/source/SourceResult.java
=> MULE-12673: fix cases when an exception occurs in an error handler

mule-extensions-api-persistence/src/main/java/org/mule/runtime/extension/internal/persistence/metadata/MetadataKeyTypeAdapter.java, mule-extensions-api-persistence/src/test/java/org/mule/runtime/extension/api/persistence/BasePersistenceTestCase.java, mule-extensions-api-persistence/src/test/java/org/mule/runtime/extension/api/persistence/MetadataKeyResultPersistenceTestCase.java, mule-extensions-api-persistence/src/test/resources/metadata/multi-level-key-result.json
(cherry picked from commit ff528e2)
=> MULE-12889: Metadata is not resolved for SOAP-based connectors

mule-extensions-api-persistence/src/main/java/org/mule/runtime/extension/internal/persistence/ExtensionModelTypeAdapter.java, mule-extensions-api-persistence/src/test/java/org/mule/runtime/extension/api/persistence/BasePersistenceTestCase.java, mule-extensions-api-persistence/src/test/java/org/mule/runtime/extension/api/persistence/LoadAndSerializeXmlExtensionModelsTestCase.java, mule-extensions-api-persistence/src/test/resources/org/mule/test/soap/extension/list-of-serialized-extension-model.json, mule-extensions-api-persistence/src/test/resources/org/mule/test/soap/extension/serialized-extension-model.json, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/annotation/PrivilegedExport.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/model/ImmutableExtensionModel.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/ExtensionModelFactory.java
_ Adding support for exporting privileged packages on extensions
=> MULE-13011: Add privileged API for plugin artifacts

mule-extensions-api/src/main/resources/META-INF/mule-module.properties
Add missing export package entry
=> MULE-13739: Wrong HTTP and WSC stereotypes

mule-extensions-api/src/main/resources/META-INF/mule-module.properties
Reverts mulesoft/mule-extensions-api#490
=> Revert "MULE-13739: Wrong HTTP and WSC stereotypes"

mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/ExtensionTypesDeclarationEnricher.java
=> MULE-14636: HTTP Connector is not including in its type catalog the declaration for Origin type

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/operation/Result.java
=> MULE-14693: Minor performance improvements

mule-extensions-api/pom.xml, mule-extensions-api/src/main/resources/META-INF/mule-module.properties, pom.xml
* Upgrade transactions-api to 1.3
=> MULE-16042: javax packages not being resolved properly on JDK11

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/operation/Result.java
* Stop abusing of Optional and lambdas
=> MULE-16101: Miscellaneous performance improvements

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/declaration/type/annotation/StereotypeTypeAnnotation.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/ExtensionTypesDeclarationEnricher.java
=> MULE-17293: Stereotypes enrichment is done before all types are

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/declaration/type/annotation/StereotypeTypeAnnotation.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/ExtensionTypesDeclarationEnricher.java
Reverts mulesoft/mule-extensions-api#653
=> Revert "MULE-17293: Stereotypes enrichment is done before all types are"

mule-extensions-api/api-changes.json, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/declaration/type/annotation/StereotypeTypeAnnotation.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/loader/DeclarationEnricherPhase.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/ExtensionTypesDeclarationEnricher.java
=> MULE-17293: Stereotypes enrichment is done before all types are (#653)

mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/ConfigRefDeclarationEnricher.java
=> MULE-17703: Validate preexisting config-ref parameter on

mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/ExtensionTypesDeclarationEnricher.java
Reverts mulesoft/mule-extensions-api#674
=> Revert "MULE-17398: Operations that return a PagingProvider do not populate the type catalog properly"

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/exception/ModuleException.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/operation/CompletableComponentExecutor.java
=> MULE-17924: Optimize error handling performance

mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/ocs/OCSConstants.java
This reverts commit eb7cb523010f1bd8e0a841903327fd224c96262a.
=> Revert "MULE-17935: add additional property (#689)"

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/dsl/syntax/XmlDslSyntaxResolver.java
=> MULE-18667: Avoid processing the same node multiple times in

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/runtime/config/ExpirableConfigurationProvider.java
This reverts commit 614b83d88e0343128f99516ece366d5bd1ae61b2.
=> MULE-18698: Revert cache changes in Dynamic Configurations

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/declaration/type/PoolingProfileTypeBuilder.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/declaration/type/TlsContextClassHandler.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/error/ErrorMapping.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/util/InfrastructureTypeMapping.java
=> MULE-18932: AST components for infrastructure types do not have the

pom.xml
(cherry picked from commit f53cc94f86f587e9e054a85f84f59b46ce398080)
=> MULE-19224: Avoid forking the Java compiler (#771)

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/annotation/connectivity/oauth/AuthorizationCode.java
Changes according to PR's review #799
=> MULE-19544 - Changed jdoc for includeRedirectUriInRefreshTokenRequest attribute on @AuthorizationCode

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/declaration/type/DefaultExtensionsTypeLoaderFactory.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/declaration/type/SchedulingStrategyClassHandler.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/api/declaration/type/SchedulingStrategyClassHandlerTestCase.java
=> MULE-19843: SchedulingStrategy param has wrong namespace when in subType

mule-extensions-api-persistence/pom.xml, pom.xml
classpath causes compilation failure in integration-tests
=> W-11271603: com.vaadin.external.google:android-json dependency in

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/loader/ExtensionLoadingContext.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/BooleanParameterDeclarationEnricher.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/internal/loader/enricher/BooleanParameterDeclarationEnricherTestCase.java
=> W-12003688: BooleanParameterDeclarationEnricher must not run for crafted

mule-extensions-api/src/test/java/org/mule/runtime/extension/api/dsl/BaseXmlDeclarationTestCase.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/api/dsl/ComposableXmlDeclarationTestCase.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/api/dsl/NoWrapperComponentXmlDeclarationTestCase.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/internal/loader/validator/NoWrapperModelValidatorTestCase.java
extensions-api and mule modules)
=> W-12724722: Extract tck from mule-api (test classes used in

pom.xml
(cherry picked from commit 123ec38d6f7071e69897b2c8423ec62ab5e757f7)
=> W-13578394 - MULE-19224: Avoid forking the build to package sources (#781)

mule-extensions-api/pom.xml
* piggyback: Add errorProneAnnotations to depMgmt
=> W-13680141: Fix split package between txw2 and jaxb-impl

mule-extensions-api/src/main/java/module-info.java, mule-extensions-soap-api/src/main/java/module-info.java
=> W-13748730: Add module-info to mule-core and services apis

mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/TargetParameterDeclarationEnricher.java
(cherry picked from commit 426dc0f2bfe2fc45e73959c0987ee477f3dd29ea)
=> W-13588449: Parse template target value breaking change. (#1014)

mule-extensions-mime-types/pom.xml
=> W-14274379: Move mime.types file from mule-core to its own jar

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/loader/ExtensionLoadingContext.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/loader/ExtensionModelLoadingRequest.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/DefaultExtensionLoadingContext.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/ExtensionModelFactory.java
* FORCE_EXTENSION_VALIDATION_PROPERTY_NAME
* SHARE_ERROR_TYPE_REPOSITORY_PROPERTY
=> W-14572236: Remove killswitches (#1306)

mule-extensions-api/api-changes.json, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/loader/ExtensionModelLoader.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/api/test/internal/loader/enricher/BooleanParameterDeclarationEnricherTestCase.java
=> W-15716727: Update ExtensionModel providers to not use extensions-api

mule-extensions-api/src/main/java/module-info.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/BooleanParameterDeclarationEnricher.java
=> W-15716727: Update ExtensionModel providers to not use extensions-api internals

mule-extensions-api-dsql/pom.xml, mule-extensions-api-dsql/src/main/java/org/mule/runtime/extension/internal/dsql/DefaultDsqlQuery.java, mule-extensions-api-dsql/src/main/java/org/mule/runtime/extension/internal/exception/DsqlParsingException.java, mule-extensions-api-dsql/src/main/java/org/mule/runtime/extension/internal/expression/EmptyExpression.java, mule-extensions-api-dsql/src/main/java/org/mule/runtime/extension/internal/expression/Function.java, mule-extensions-api-dsql/src/main/java/org/mule/runtime/extension/internal/expression/Not.java, mule-extensions-api-dsql/src/main/java/org/mule/runtime/extension/internal/grammar/QueryModelDirectionFactory.java, mule-extensions-api-dsql/src/main/java/org/mule/runtime/extension/internal/grammar/QueryModelOperatorFactory.java, pom.xml
* Extract common release config
=> W-15609911: Provide a common parent pom with pluginManangement of common

mule-extensions-api/src/main/java/module-info.java
=> W-15808825: KryoException when a batch step fails with a ModuleException

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/declaration/type/ExtensionObjectTypeHandler.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/dsl/syntax/XmlDslSyntaxResolver.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/loader/ExtensionLoadingContext.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/CachedClassTypeLoader.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/DefaultExtensionLoadingContext.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/OAuthDeclarationEnricher.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/RedeliveryPolicyDeclarationEnricher.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/TargetParameterDeclarationEnricher.java, mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/enricher/TransactionalDeclarationEnricher.java
* Reuse the same caching type loader for all type loads done for an extension model, making it avaliable in the extensionLoadingContext
=> W-16517517: Cache loaded java types for an extension

mule-extensions-api/pom.xml
Explicitly add used `caffeine` dependency
=> W-16985658: Properly manage sdk-api dependencies

mule-extensions-api/src/main/java/org/mule/runtime/extension/api/dsl/syntax/resources/spi/ExtensionSchemaGenerator.java
=> W-17316991: Reuse DslSyntaxResolver's during app deployment

mule-extensions-api/src/main/java/module-info.java, mule-extensions-api/src/test/java/org/mule/runtime/extension/api/test/mimetype/FileExtensionContentTypeResolutionTestCase.java
This reverts commit 9ce2535e69b858d5c45e4588073c7dd9156dee91.
=> Revert "W-17281517: Upgrade jakarta dependencies (#1174)"

mule-extensions-api/api-changes.json, mule-extensions-api/src/main/java/org/mule/runtime/extension/api/util/ExtensionModelUtils.java
(#1201)
* Reintroduce getConfigurationForComponent
=> W-17599201: Enrich extension model with implicit configs metadata
